[package]
name = "candle-macros-types"
version.workspace = true
edition.workspace = true
description = "Type definitions for Candle procedural macros"
repository.workspace = true
license.workspace = true

[features]
default = []
cuda = ["dep:cudarc"]
metal = ["dep:metal"]

[dependencies]
cudarc = { workspace = true, optional = true }
metal = { version = "0.29.0", optional = true }
